import { useState, useEffect } from 'react';

export default function Guru() {
  const [data, setData] = useState(null);
  const [tanggalList, setTanggalList] = useState([]);
  const [tanggalPilih, setTanggalPilih] = useState('');
  const [salinText, setSalinText] = useState('');
  const [guruLogin, setGuruLogin] = useState('');

  useEffect(() => {
    const user = localStorage.getItem('guru_login');
    if (!user) {
      window.location.href = '/'; // kalau belum login, balik ke index
    } else {
      setGuruLogin(user);
    }

    fetch('/hasil.json')
      .then(r => r.json())
      .then(json => {
        setData(json);
        const keys = Object.keys(json.absensi || {}).sort((a, b) => new Date(b) - new Date(a));
        setTanggalList(keys);
        setTanggalPilih(keys[0] || '');
      });
  }, []);

  const buatTeks = (tgl) => {
    if (!data || !tgl || !data.absensi[tgl]) return '';
    let teks = `Rekap Absensi Kelas ${data.kelas} (Wali: ${data.wali_kelas})\nTanggal: ${tgl}\n\n`;
    data.absensi[tgl].forEach((r, i) => {
      teks += `${i + 1}. ${r.nama} | Sekolah: ${r.sekolah} | Shalat: ${r.shalat}\n`;
    });
    teks += `\n---\nGenerated by Sistem Absensi Sekolah\n© 2025 - Created by Rizky`;
    return teks;
  };

  const salinKeClipboard = () => {
    const teks = buatTeks(tanggalPilih);
    if (!teks) {
      alert('Tidak ada data untuk tanggal yang dipilih.');
      return;
    }
    setSalinText(teks);
    navigator.clipboard.writeText(teks);
    alert(`Hasil absensi tanggal ${tanggalPilih} berhasil disalin ke clipboard!`);
  };

  const logoutGuru = () => {
    localStorage.removeItem('guru_login');
    window.location.href = '/';
  };

  if (!data) return <p className="p-6 text-center text-white">Memuat data...</p>;

  return (
    <div className="min-h-screen bg-gradient-to-br from-gray-900 via-indigo-900 to-purple-900 text-white p-6">
      <div className="max-w-4xl mx-auto bg-gray-900/80 p-6 rounded-2xl shadow-2xl border border-indigo-400/50">
        <div className="flex justify-between items-center mb-4">
          <p className="text-sm text-gray-300">Login sebagai: <b>{guruLogin}</b></p>
          <button
            onClick={logoutGuru}
            className="bg-red-600 hover:bg-red-700 text-white px-4 py-1 rounded-lg text-sm"
          >
            Logout
          </button>
        </div>

        <h2 className="text-2xl font-bold mb-2 text-indigo-200 drop-shadow-lg">Rekap Absensi</h2>
        <p className="text-gray-300 mb-4">
          Kelas: {data.kelas} | Wali Kelas: {data.wali_kelas}
        </p>

        {/* Pilih tanggal */}
        <div className="my-4">
          <label className="text-gray-300">
            Pilih tanggal: 
            <select
              className="ml-2 px-3 py-1 rounded bg-gray-800 text-white border border-indigo-400"
              value={tanggalPilih}
              onChange={e => setTanggalPilih(e.target.value)}
            >
              {tanggalList.map(tgl => (
                <option key={tgl} value={tgl}>{tgl}</option>
              ))}
            </select>
          </label>
        </div>

        {/* Tombol Salin */}
        <button
          onClick={salinKeClipboard}
          className="bg-green-500 hover:bg-green-600 text-white px-6 py-2 rounded-lg mb-4 shadow-lg hover:shadow-green-500/50 transition-all"
        >
          Salin Hasil (Teks)
        </button>

        {/* Tabel Absensi */}
        <table className="table-auto w-full text-left border border-gray-700 rounded-lg overflow-hidden">
          <thead>
            <tr className="bg-indigo-700 text-white">
              <th className="px-4 py-2">No</th>
              <th className="px-4 py-2">Nama</th>
              <th className="px-4 py-2">Absen Sekolah</th>
              <th className="px-4 py-2">Absen Shalat</th>
            </tr>
          </thead>
          <tbody>
            {tanggalPilih && data.absensi[tanggalPilih] ? (
              data.absensi[tanggalPilih].map((r, i) => (
                <tr key={i} className="border-t border-gray-700 hover:bg-gray-800 transition">
                  <td className="px-4 py-2">{i + 1}</td>
                  <td className="px-4 py-2">{r.nama}</td>
                  <td className="px-4 py-2">{r.sekolah}</td>
                  <td className="px-4 py-2">{r.shalat}</td>
                </tr>
              ))
            ) : (
              <tr><td colSpan={4} className="text-center p-4 text-gray-400">Tidak ada data</td></tr>
            )}
          </tbody>
        </table>

        {/* Credit Footer */}
        <div className="mt-6 text-center text-gray-400 text-sm">
          ---<br />
          Generated by <b>Sistem Absensi Sekolah</b><br />
          © 2025 - Created by <b>Rizky</b>
        </div>

        {/* Preview Teks */}
        <textarea
          className="w-full mt-4 p-3 rounded-lg bg-gray-800 text-sm text-gray-100 border border-gray-700"
          rows={6}
          readOnly
          value={salinText}
          placeholder="Hasil salinan akan muncul di sini setelah klik 'Salin Hasil (Teks)'"
        ></textarea>
      </div>
    </div>
  );
                                             }
